// Generated from the Figma file (PinReal. v2). Every asset is a local copy under
// /public/images/pinreal/design — no references to temporary Figma URLs.

export const hero = {
  CheckIcon: "/images/pinreal/design/hero/CheckIcon.svg",
  Ellipse: "/images/pinreal/design/hero/Ellipse.svg",
  Ellipse1: "/images/pinreal/design/hero/Ellipse1.svg",
  HomepageLockedPinReal: "/images/pinreal/design/hero/HomepageLockedPinReal.webp",
  ScreenToUpdate: "/images/pinreal/design/hero/ScreenToUpdate.webp",
  ScreenToUpdate1: "/images/pinreal/design/hero/ScreenToUpdate1.webp",
  Send: "/images/pinreal/design/hero/Send.svg",
} as const;

export const title = {
  FigmaLogo: "/images/pinreal/design/title/FigmaLogo.svg",
  MiroMiroIcon01: "/images/pinreal/design/title/MiroMiroIcon01.svg",
  PinIcon: "/images/pinreal/design/title/PinIcon.svg",
} as const;

export const brand = {
  "1": "/images/pinreal/design/brand/1.svg",
  Camera: "/images/pinreal/design/brand/Camera.svg",
  Img: "/images/pinreal/design/brand/Img.svg",
  Line6: "/images/pinreal/design/brand/Line6.svg",
  Line7: "/images/pinreal/design/brand/Line7.svg",
  Vector: "/images/pinreal/design/brand/Vector.svg",
} as const;

export const ds = {
  PinIcon: "/images/pinreal/design/ds/PinIcon.svg",
  PinIcon1: "/images/pinreal/design/ds/PinIcon1.svg",
  PinIcon2: "/images/pinreal/design/ds/PinIcon2.svg",
  PinIcon3: "/images/pinreal/design/ds/PinIcon3.svg",
  PinIcon4: "/images/pinreal/design/ds/PinIcon4.svg",
  PinIcon5: "/images/pinreal/design/ds/PinIcon5.svg",
  TableLines: "/images/pinreal/design/ds/TableLines.svg",
} as const;

export const personas = {
  Picture: "/images/pinreal/design/personas/Picture.webp",
  Picture1: "/images/pinreal/design/personas/Picture1.webp",
  Picture2: "/images/pinreal/design/personas/Picture2.webp",
  Shadow: "/images/pinreal/design/personas/Shadow.svg",
} as const;

export const icons = {
  CheckIcon: "/images/pinreal/design/icons/CheckIcon.svg",
  AddIcon1: "/images/pinreal/design/icons/AddIcon1.svg",
  BackArrow: "/images/pinreal/design/icons/BackArrow.svg",
  BackArrow1: "/images/pinreal/design/icons/BackArrow1.svg",
  Checkbox1: "/images/pinreal/design/icons/Checkbox1.svg",
  Checkbox2: "/images/pinreal/design/icons/Checkbox2.svg",
  Checkbox3: "/images/pinreal/design/icons/Checkbox3.svg",
  Crop: "/images/pinreal/design/icons/Crop.svg",
  CropButton: "/images/pinreal/design/icons/CropButton.svg",
  DropUpButton: "/images/pinreal/design/icons/DropUpButton.svg",
  EditAddPlusCircle: "/images/pinreal/design/icons/EditAddPlusCircle.svg",
  EditAddPlusCircle1: "/images/pinreal/design/icons/EditAddPlusCircle1.svg",
  EditIcon: "/images/pinreal/design/icons/EditIcon.svg",
  Emoji: "/images/pinreal/design/icons/Emoji.svg",
  Line3: "/images/pinreal/design/icons/Line3.svg",
  Line4: "/images/pinreal/design/icons/Line4.svg",
  Line5: "/images/pinreal/design/icons/Line5.svg",
  Line6: "/images/pinreal/design/icons/Line6.svg",
  Line7: "/images/pinreal/design/icons/Line7.svg",
  Mic: "/images/pinreal/design/icons/Mic.svg",
  Pin2: "/images/pinreal/design/icons/Pin2.svg",
  Pin3: "/images/pinreal/design/icons/Pin3.svg",
  Pin4: "/images/pinreal/design/icons/Pin4.svg",
  PinIcon: "/images/pinreal/design/icons/PinIcon.svg",
  PinIcon1: "/images/pinreal/design/icons/PinIcon1.svg",
  ProfilePicture: "/images/pinreal/design/icons/ProfilePicture.webp",
  Property1CommentIcon1: "/images/pinreal/design/icons/Property1CommentIcon1.svg",
  Property1Default: "/images/pinreal/design/icons/Property1Default.svg",
  Property1Default1: "/images/pinreal/design/icons/Property1Default1.svg",
  Property1Default2: "/images/pinreal/design/icons/Property1Default2.svg",
  Property1Default3: "/images/pinreal/design/icons/Property1Default3.svg",
  Property1MessageIcon: "/images/pinreal/design/icons/Property1MessageIcon.svg",
  Property1NotificationBell: "/images/pinreal/design/icons/Property1NotificationBell.svg",
  Property1NotificationBellWithNotifc: "/images/pinreal/design/icons/Property1NotificationBellWithNotifc.svg",
  Property1PaperPlane: "/images/pinreal/design/icons/Property1PaperPlane.svg",
  Property1ReactIcon: "/images/pinreal/design/icons/Property1ReactIcon.svg",
  Property1SwichtLeft: "/images/pinreal/design/icons/Property1SwichtLeft.svg",
  Property1SwichtRight: "/images/pinreal/design/icons/Property1SwichtRight.svg",
  Property1Variant2: "/images/pinreal/design/icons/Property1Variant2.svg",
  Property1Variant3: "/images/pinreal/design/icons/Property1Variant3.svg",
  Property1Variant4: "/images/pinreal/design/icons/Property1Variant4.svg",
  Property1Variant5: "/images/pinreal/design/icons/Property1Variant5.svg",
  Property1Variant6: "/images/pinreal/design/icons/Property1Variant6.svg",
  Rectangle20: "/images/pinreal/design/icons/Rectangle20.webp",
  Rectangle21: "/images/pinreal/design/icons/Rectangle21.webp",
  Rectangle22: "/images/pinreal/design/icons/Rectangle22.webp",
  Rectangle23: "/images/pinreal/design/icons/Rectangle23.webp",
  Rectangle24: "/images/pinreal/design/icons/Rectangle24.webp",
  SelfieImage3: "/images/pinreal/design/icons/SelfieImage3.webp",
  Send: "/images/pinreal/design/icons/Send.svg",
  Slider1: "/images/pinreal/design/icons/Slider1.svg",
  Slider2: "/images/pinreal/design/icons/Slider2.svg",
  Vector: "/images/pinreal/design/icons/Vector.svg",
  Vector1: "/images/pinreal/design/icons/Vector1.svg",
  Vector2: "/images/pinreal/design/icons/Vector2.svg",
  Vector3: "/images/pinreal/design/icons/Vector3.svg",
} as const;

export const intro = {
  Iphone141: "/images/pinreal/design/intro/Iphone141.webp",
  ScreenToUpdate: "/images/pinreal/design/intro/ScreenToUpdate.webp",
  ScreenToUpdate1: "/images/pinreal/design/intro/ScreenToUpdate1.webp",
  ScreenToUpdate2: "/images/pinreal/design/intro/ScreenToUpdate2.webp",
  ScreenToUpdate3: "/images/pinreal/design/intro/ScreenToUpdate3.webp",
  ScreenToUpdate4: "/images/pinreal/design/intro/ScreenToUpdate4.webp",
} as const;

export const ui = {
  AlejandraRiosLh56T1ASz8Unsplash1: "/images/pinreal/design/ui/AlejandraRiosLh56T1ASz8Unsplash1.webp",
  AlejandraRiosLh56T1ASz8Unsplash2: "/images/pinreal/design/ui/AlejandraRiosLh56T1ASz8Unsplash2.webp",
  AlejandraRiosLh56T1ASz8Unsplash3: "/images/pinreal/design/ui/AlejandraRiosLh56T1ASz8Unsplash3.webp",
  AlejandraRiosLh56T1ASz8Unsplash4: "/images/pinreal/design/ui/AlejandraRiosLh56T1ASz8Unsplash4.webp",
  Battery: "/images/pinreal/design/ui/Battery.svg",
  Battery1: "/images/pinreal/design/ui/Battery1.svg",
  CellularConnection: "/images/pinreal/design/ui/CellularConnection.svg",
  CellularConnection1: "/images/pinreal/design/ui/CellularConnection1.svg",
  CommentIcon1: "/images/pinreal/design/ui/CommentIcon1.svg",
  CommentIcon2: "/images/pinreal/design/ui/CommentIcon2.svg",
  CommunicationPaperPlane: "/images/pinreal/design/ui/CommunicationPaperPlane.svg",
  CommunicationPaperPlane1: "/images/pinreal/design/ui/CommunicationPaperPlane1.svg",
  CreateIcon: "/images/pinreal/design/ui/CreateIcon.svg",
  CreateIcon1: "/images/pinreal/design/ui/CreateIcon1.svg",
  ExploreIcon: "/images/pinreal/design/ui/ExploreIcon.svg",
  ExploreIcon1: "/images/pinreal/design/ui/ExploreIcon1.svg",
  HomeIcon: "/images/pinreal/design/ui/HomeIcon.svg",
  HomeIcon1: "/images/pinreal/design/ui/HomeIcon1.svg",
  Image3: "/images/pinreal/design/ui/Image3.webp",
  Image4: "/images/pinreal/design/ui/Image4.webp",
  Image5: "/images/pinreal/design/ui/Image5.webp",
  JunkoNakaseQ72Wa97DgUnsplash1: "/images/pinreal/design/ui/JunkoNakaseQ72Wa97DgUnsplash1.webp",
  JunkoNakaseQ72Wa97DgUnsplash2: "/images/pinreal/design/ui/JunkoNakaseQ72Wa97DgUnsplash2.webp",
  KatieSmithUQs1802D0CqUnsplash1: "/images/pinreal/design/ui/KatieSmithUQs1802D0CqUnsplash1.webp",
  KatieSmithUQs1802D0CqUnsplash2: "/images/pinreal/design/ui/KatieSmithUQs1802D0CqUnsplash2.webp",
  KatieSmithUQs1802D0CqUnsplash3: "/images/pinreal/design/ui/KatieSmithUQs1802D0CqUnsplash3.webp",
  Line2: "/images/pinreal/design/ui/Line2.svg",
  Line3: "/images/pinreal/design/ui/Line3.svg",
  MariaOrlovaB37MDyPzdJmUnsplash1: "/images/pinreal/design/ui/MariaOrlovaB37MDyPzdJmUnsplash1.webp",
  MariaOrlovaB37MDyPzdJmUnsplash2: "/images/pinreal/design/ui/MariaOrlovaB37MDyPzdJmUnsplash2.webp",
  MenuMoreHorizontal: "/images/pinreal/design/ui/MenuMoreHorizontal.svg",
  MenuMoreHorizontal1: "/images/pinreal/design/ui/MenuMoreHorizontal1.svg",
  MessageIcon: "/images/pinreal/design/ui/MessageIcon.svg",
  NotificationBellWithNotifc: "/images/pinreal/design/ui/NotificationBellWithNotifc.svg",
  PinIcon: "/images/pinreal/design/ui/PinIcon.svg",
  PinIcon1: "/images/pinreal/design/ui/PinIcon1.svg",
  PinIcon2: "/images/pinreal/design/ui/PinIcon2.svg",
  PinRealIcon: "/images/pinreal/design/ui/PinRealIcon.svg",
  PinRealIcon1: "/images/pinreal/design/ui/PinRealIcon1.svg",
  ProfilePicture: "/images/pinreal/design/ui/ProfilePicture.webp",
  ProfilePicture1: "/images/pinreal/design/ui/ProfilePicture1.webp",
  ProfilePicture2: "/images/pinreal/design/ui/ProfilePicture2.webp",
  ProfilePicture3: "/images/pinreal/design/ui/ProfilePicture3.webp",
  ProfilePicture4: "/images/pinreal/design/ui/ProfilePicture4.webp",
  ReactIcon: "/images/pinreal/design/ui/ReactIcon.svg",
  Rectangle5: "/images/pinreal/design/ui/Rectangle5.svg",
  ScreenToUpdate: "/images/pinreal/design/ui/ScreenToUpdate.webp",
  ScreenToUpdate1: "/images/pinreal/design/ui/ScreenToUpdate1.webp",
  ScreenToUpdate10: "/images/pinreal/design/ui/ScreenToUpdate10.webp",
  ScreenToUpdate11: "/images/pinreal/design/ui/ScreenToUpdate11.webp",
  ScreenToUpdate12: "/images/pinreal/design/ui/ScreenToUpdate12.webp",
  ScreenToUpdate13: "/images/pinreal/design/ui/ScreenToUpdate13.webp",
  ScreenToUpdate14: "/images/pinreal/design/ui/ScreenToUpdate14.webp",
  ScreenToUpdate15: "/images/pinreal/design/ui/ScreenToUpdate15.webp",
  ScreenToUpdate16: "/images/pinreal/design/ui/ScreenToUpdate16.webp",
  ScreenToUpdate17: "/images/pinreal/design/ui/ScreenToUpdate17.webp",
  ScreenToUpdate18: "/images/pinreal/design/ui/ScreenToUpdate18.webp",
  ScreenToUpdate2: "/images/pinreal/design/ui/ScreenToUpdate2.webp",
  ScreenToUpdate3: "/images/pinreal/design/ui/ScreenToUpdate3.webp",
  ScreenToUpdate4: "/images/pinreal/design/ui/ScreenToUpdate4.webp",
  ScreenToUpdate5: "/images/pinreal/design/ui/ScreenToUpdate5.webp",
  ScreenToUpdate6: "/images/pinreal/design/ui/ScreenToUpdate6.webp",
  ScreenToUpdate7: "/images/pinreal/design/ui/ScreenToUpdate7.webp",
  ScreenToUpdate8: "/images/pinreal/design/ui/ScreenToUpdate8.webp",
  ScreenToUpdate9: "/images/pinreal/design/ui/ScreenToUpdate9.webp",
  SelfieImage3: "/images/pinreal/design/ui/SelfieImage3.webp",
  SelfieImage4: "/images/pinreal/design/ui/SelfieImage4.webp",
  SelfieImage5: "/images/pinreal/design/ui/SelfieImage5.webp",
  SplashScreen: "/images/pinreal/design/ui/SplashScreen.webp",
  UpperDivider: "/images/pinreal/design/ui/UpperDivider.svg",
  UpperDivider1: "/images/pinreal/design/ui/UpperDivider1.svg",
  UserUserCircle: "/images/pinreal/design/ui/UserUserCircle.svg",
  Vector: "/images/pinreal/design/ui/Vector.svg",
  Vector1: "/images/pinreal/design/ui/Vector1.svg",
  Vector2: "/images/pinreal/design/ui/Vector2.svg",
  Vector3: "/images/pinreal/design/ui/Vector3.svg",
  VerticalMoreIcon: "/images/pinreal/design/ui/VerticalMoreIcon.svg",
  Wifi: "/images/pinreal/design/ui/Wifi.svg",
  Wifi1: "/images/pinreal/design/ui/Wifi1.svg",
} as const;

export const closing = {
  Glow: "/images/pinreal/design/closing/Glow.svg",
  PinIcon: "/images/pinreal/design/closing/PinIcon.svg",
  PinIcon1: "/images/pinreal/design/closing/PinIcon1.svg",
} as const;

export const flow = {
  UserFlowDiagramWithoutCaptions: "/images/pinreal/design/flow/UserFlowDiagramWithoutCaptions.webp",
} as const;
